# Generated by Django 4.2.7 on 2023-12-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
    ]
